language: java
jdk:
- oraclejdk8
addons:
  artifacts:
    key:
      secure: EuP+LdFDhqBWNgmY5y+DawSX56vIWPfHPjCaDxfaAfbIBcJCimgknGRwB8UVEOzQSwZ0Dpael95cKHdjwzLbOENTBnEc1zjOlNaScx8EKPyIRVuGCTv+U7NibL6UFuNZqZb6sTpqREFhwyWXxgX+5gb4zRLFD2vqM9REnvAU1eQ=
    secret:
      secure: a1dZiTJ2GoIsOt02JKKDO+P4TeLjBSJ3OT7g7SsTKaFSO0yVCB/vNjALEBdk982oIy6IBPPefLGmazmzEHP7ebNSPIHxjPhplPi4enP7QIDzyLaHkE9T5EVsqx5GpFIrp4g0kmzZ8k0Q3izqEP1ZtNatArB0bjKEhzEjYVuwy74=
    bucket: java-ding
deploy:
  provider: releases
  api_key:
    secure: iLMaFjeeXOK+IokVsYwMFGrzEVZ5xBqnvVDlrJSgSnZQxFCMd5L4e1eUvS4DvyTK2hXBsvad0o+HQd2tAavUEDzPYPBfAGrr6IDzh0P49C5DCQDVjv6cyUPVK9n6mBbQz7G4onCK3GQzYqITHcsaAjeuy0dVmVB3IbIcGsM4gkg=
  file: build/libs/*.jar
  on:
    repo: torstenwerner/ding
